name: POJA Import CI

on:
  push:
    branches:
      - import/a10bc01f-8002-4630-8413-879babc52a0f
env:
  ORG_ID: 107abe9e-ac83-4973-9fd1-df8b5354503b
  IMPORT_ID: a10bc01f-8002-4630-8413-879babc52a0f

jobs:
  post-transformation-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    

    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Run tests and capture outcome
        id: test
        continue-on-error: true
        run: |
          set -o pipefail
          if [ -f "build.gradle" ]; then
            chmod +x gradlew
            ./gradlew test
          elif [ -f "pom.xml" ]; then
            chmod +x mvnw
            mvnw test
          else
            echo "No build tool detected!" >&2
            exit 1
          fi

          EXIT_CODE=$?

          if [ $EXIT_CODE -eq 0 ]; then
            echo "outcome=SUCCESS" >> $GITHUB_OUTPUT
          else
            echo "outcome=FAILURE" >> $GITHUB_OUTPUT
          fi

      - name: Update import state
        run: |
          OUTCOME="${{ steps.test.outputs.outcome }}"
          RUN_ID="${{ github.run_id }}"
          ATTEMPT_NB="${{ github.run_attempt }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.repository.split('/')[1] }}"


      - name: Update import state
        run: |
          curl --fail -X POST "https://api.preprod.poja.io/orgs/${{ env.ORG_ID }}/imports/${{ env.IMPORT_ID }}/states" \
            -H "Authorization: AppBearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
                  --arg job_name "PRE_TRANSFORMATION_TEST" \
                  --arg job_status "${{ steps.test.outputs.outcome }}" \
                  --arg run_id "${{ github.run_id }}" \
                  --arg attempt_nb "${{ github.run_attempt }}" \
                  --arg repo_owner "${{ github.repository_owner }}" \
                  --arg repo_name "${{ github.repository.split('/')[1] }}" \
                  '{ job_name: $job_name, job_status: $job_status, run_id: $run_id, attempt_nb: $attempt_nb, repo_owner: $repo_owner, repo_name: $repo_name }')"
